name: app_praca_ciencia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.28.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.5.0

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  interactive_image: ^7.0.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.1.14

  intl: 0.20.2
  mask_text_input_formatter: ^2.4.0
  flutter_localization: ^0.2.1
  table_calendar: ^3.1.3
  shared_preferences: ^2.2.2
  mailer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
